-- Creación de la tabla para sincronización de sistemas de seguridad
CREATE TABLE Sistemas_Seguridad (
    id_sistema          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_sistema      VARCHAR2(100) NOT NULL,
    tipo_sistema        VARCHAR2(50) CHECK (tipo_sistema IN ('Control de Acceso', 'Cámaras', 'Sensores', 'Alarmas', 'Mantenimiento')),
    estado_sistema      VARCHAR2(20) CHECK (estado_sistema IN ('Activo', 'Inactivo')),
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    detalles            CLOB
);

-- Tabla para integración con software empresarial
CREATE TABLE Integracion_Software (
    id_integracion      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origen      NUMBER REFERENCES Sistemas_Seguridad(id_sistema),
    software_destino    VARCHAR2(100) NOT NULL,
    tipo_software       VARCHAR2(50) CHECK (tipo_software IN ('ERP', 'HRM', 'Otro')),
    estado_integracion  VARCHAR2(20) CHECK (estado_integracion IN ('Exitoso', 'Fallido', 'Pendiente')),
    fecha_sincronizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    detalles            CLOB
);

-- Tabla para respaldos de datos
CREATE TABLE Respaldo_Datos (
    id_respaldo         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_respaldo       VARCHAR2(50) CHECK (tipo_respaldo IN ('Nube', 'Servidor Local')),
    fecha_respaldo      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado_respaldo     VARCHAR2(20) CHECK (estado_respaldo IN ('Exitoso', 'Fallido')),
    tamano_respaldo     NUMBER, -- En MB
    detalles            CLOB
);

-- Tabla para auditoría
CREATE TABLE Auditoria_Integracion (
    id_auditoria        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_evento         VARCHAR2(50) CHECK (tipo_evento IN ('Sincronización', 'Mantenimiento', 'Actualización')),
    id_referencia       NUMBER,
    descripcion_evento  CLOB,
    fecha_evento        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Trigger para registrar eventos de actualización en Sistemas_Seguridad
CREATE OR REPLACE TRIGGER trg_sistemas_actualizacion
AFTER UPDATE ON Sistemas_Seguridad
FOR EACH ROW
BEGIN
    INSERT INTO Auditoria_Integracion (tipo_evento, id_referencia, descripcion_evento, fecha_evento)
    VALUES ('Actualización', :NEW.id_sistema, 'Actualización del sistema: ' || :NEW.nombre_sistema, SYSTIMESTAMP);
END;
/

-- Procedimiento para sincronizar sistemas con software empresarial
CREATE OR REPLACE PROCEDURE sincronizar_sistema (
    p_id_sistema       NUMBER,
    p_software_destino VARCHAR2,
    p_tipo_software    VARCHAR2
) AS
BEGIN
    INSERT INTO Integracion_Software (sistema_origen, software_destino, tipo_software, estado_integracion, fecha_sincronizacion)
    VALUES (p_id_sistema, p_software_destino, p_tipo_software, 'Pendiente', SYSTIMESTAMP);

    -- Simular proceso de sincronización
    UPDATE Integracion_Software
    SET estado_integracion = 'Exitoso'
    WHERE sistema_origen = p_id_sistema
      AND software_destino = p_software_destino;

    -- Registrar evento en auditoría
    INSERT INTO Auditoria_Integracion (tipo_evento, id_referencia, descripcion_evento, fecha_evento)
    VALUES ('Sincronización', p_id_sistema, 'Sincronización con software: ' || p_software_destino, SYSTIMESTAMP);
END;
/

-- Procedimiento para respaldar datos
CREATE OR REPLACE PROCEDURE respaldar_datos (
    p_tipo_respaldo VARCHAR2,
    p_tamano_respaldo NUMBER
) AS
BEGIN
    INSERT INTO Respaldo_Datos (tipo_respaldo, fecha_respaldo, estado_respaldo, tamano_respaldo)
    VALUES (p_tipo_respaldo, SYSTIMESTAMP, 'Exitoso', p_tamano_respaldo);

    -- Registrar evento en auditoría
    INSERT INTO Auditoria_Integracion (tipo_evento, descripcion_evento, fecha_evento)
    VALUES ('Respaldo', 'Respaldo de datos tipo: ' || p_tipo_respaldo, SYSTIMESTAMP);
END;
/

-- Vista para consultar estado de integraciones
CREATE OR REPLACE VIEW vw_estado_integraciones AS
SELECT
    ss.nombre_sistema,
    isw.software_destino,
    isw.tipo_software,
    isw.estado_integracion,
    isw.fecha_sincronizacion
FROM
    Sistemas_Seguridad ss
    JOIN Integracion_Software isw ON ss.id_sistema = isw.sistema_origen;

-- Vista para reportes de auditoría
CREATE OR REPLACE VIEW vw_reporte_auditoria AS
SELECT
    ai.tipo_evento,
    ai.descripcion_evento,
    ai.fecha_evento
FROM
    Auditoria_Integracion ai
ORDER BY
    ai.fecha_evento DESC;
