-- SCRIPT: Tabla de Notificaciones
CREATE TABLE NOTIFICACIONES (
    ID_NOTIFICACION NUMBER PRIMARY KEY,
    TIPO VARCHAR2(50),
    MENSAJE VARCHAR2(500),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE'
);

-- SCRIPT: Tabla de Eventos
CREATE TABLE EVENTOS (
    ID_EVENTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(500),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    PRIORIDAD VARCHAR2(20),
    ESTADO VARCHAR2(20)
);

-- SCRIPT: Tabla de Notificaciones de Eventos
CREATE TABLE NOTIFICACIONES_EVENTOS (
    ID_NOTIFICACION_EVENTO NUMBER PRIMARY KEY,
    ID_NOTIFICACION NUMBER REFERENCES NOTIFICACIONES(ID_NOTIFICACION),
    ID_EVENTO NUMBER REFERENCES EVENTOS(ID_EVENTO),
    FECHA_ASIGNACION DATE DEFAULT SYSDATE
);

-- SCRIPT: Tabla de Responsables de Eventos
CREATE TABLE RESPONSABLES_EVENTOS (
    ID_RESPONSABLE_EVENTO NUMBER PRIMARY KEY,
    ID_EVENTO NUMBER REFERENCES EVENTOS(ID_EVENTO),
    NOMBRE_RESPONSABLE VARCHAR2(100),
    CONTACTO_RESPONSABLE VARCHAR2(100),
    FECHA_ASIGNACION DATE DEFAULT SYSDATE
);

-- SCRIPT: Tabla de Auditorías
CREATE TABLE AUDITORIAS (
    ID_AUDITORIA NUMBER PRIMARY KEY,
    ENTIDAD VARCHAR2(50),
    ACCION VARCHAR2(50),
    DETALLE VARCHAR2(500),
    FECHA_ACCION DATE DEFAULT SYSDATE,
    USUARIO_RESPONSABLE VARCHAR2(100)
);

-- SCRIPT: Secuencias
CREATE SEQUENCE SEQ_NOTIFICACIONES START WITH 1;
CREATE SEQUENCE SEQ_EVENTOS START WITH 1;
CREATE SEQUENCE SEQ_NOTIFICACIONES_EVENTOS START WITH 1;
CREATE SEQUENCE SEQ_RESPONSABLES_EVENTOS START WITH 1;
CREATE SEQUENCE SEQ_AUDITORIAS START WITH 1;

-- SCRIPT: Triggers para generación de IDs automáticos
CREATE OR REPLACE TRIGGER TRG_NOTIFICACIONES_BI
BEFORE INSERT ON NOTIFICACIONES
FOR EACH ROW
BEGIN
    :NEW.ID_NOTIFICACION := SEQ_NOTIFICACIONES.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_EVENTOS_BI
BEFORE INSERT ON EVENTOS
FOR EACH ROW
BEGIN
    :NEW.ID_EVENTO := SEQ_EVENTOS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_NOTIFICACIONES_EVENTOS_BI
BEFORE INSERT ON NOTIFICACIONES_EVENTOS
FOR EACH ROW
BEGIN
    :NEW.ID_NOTIFICACION_EVENTO := SEQ_NOTIFICACIONES_EVENTOS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_RESPONSABLES_EVENTOS_BI
BEFORE INSERT ON RESPONSABLES_EVENTOS
FOR EACH ROW
BEGIN
    :NEW.ID_RESPONSABLE_EVENTO := SEQ_RESPONSABLES_EVENTOS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDITORIAS_BI
BEFORE INSERT ON AUDITORIAS
FOR EACH ROW
BEGIN
    :NEW.ID_AUDITORIA := SEQ_AUDITORIAS.NEXTVAL;
END;
/

-- SCRIPT: Índices para optimización
CREATE INDEX IDX_EVENTOS_ESTADO ON EVENTOS(ESTADO);
CREATE INDEX IDX_NOTIFICACIONES_ESTADO ON NOTIFICACIONES(ESTADO);
CREATE INDEX IDX_RESPONSABLES_EVENTOS_ID_EVENTO ON RESPONSABLES_EVENTOS(ID_EVENTO);
